In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("Indicateur/base_indic_complete.csv")
df_2024 = df[df['ANNEE'] == 2024]
df_2024.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_32824\211525267.py:1: DtypeWarning: Columns (6,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Indicateur/base_indic_complete.csv")

,NUMERO,LAMBX_93,LAMBY_93,LAMBX_2,LAMBY_2,ANNEE,code_insee_commune,commune,code_insee_de_la_region,region,...,ind_sec_T2_25,ind_sec_T2_5,ind_sec_T3_25,ind_sec_T3_5,ind_sec_T4_25,ind_sec_T4_5,ind_sec_T1_off,ind_sec_T2_off,ind_sec_T3_off,ind_sec_T4_off
237408,1860,111467,6838785,60000,2401000,2024,29084,Île-Molène,53,Bretagne,...,0,0,0,0,0,0,0,0,0,0
237409,2477,127137,6798687,76000,2361000,2024,29168,Plogoff,53,Bretagne,...,0,0,0,0,0,0,0,0,0,0
237410,1984,127392,6830663,76000,2393000,2024,29190,Plougonvelin,53,Bretagne,...,0,0,0,0,0,0,0,0,0,0
237411,1861,127455,6838657,76000,2401000,2024,29201,Ploumoguer,53,Bretagne,...,0,0,0,0,0,0,0,0,0,0
237412,1737,127519,6846652,76000,2409000,2024,29098,Lampaul-Plouarzel,53,Bretagne,...,0,0,0,0,0,0,0,0,0,0

In [31]:
df_2024 = df[df['ANNEE'] == 2011]
df_2024[['ind_sec_T1_25', 'ind_sec_T1_5','ind_sec_T2_25', 'ind_sec_T2_5', 'ind_sec_T3_25','ind_sec_T3_5','ind_sec_T4_25','ind_sec_T4_5','ind_sec_T1_off',"ind_sec_T2_off","ind_sec_T3_off",	'ind_sec_T4_off']].describe()

,ind_sec_T1_25,ind_sec_T1_5,ind_sec_T2_25,ind_sec_T2_5,ind_sec_T3_25,ind_sec_T3_5,ind_sec_T4_25,ind_sec_T4_5,ind_sec_T1_off,ind_sec_T2_off,ind_sec_T3_off,ind_sec_T4_off
count,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000
mean,0.295896,0.018500,0.923170,0.808330,0.463101,0.090679,0.732612,0.092802,0.005358,0.728771,0.078751,0.043166
std,0.456467,0.134757,0.266335,0.393635,0.498662,0.287167,0.442619,0.290170,0.073005,0.444617,0.269363,0.203241
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000